### ISSUE TITLE
Not updated for Winter '18

### ISSUE THREAD

**Issue by cceremuga** [salesforce-ux/design-system-ui-kit#10]
The changes to the SLDS were significant in Winter '18, are there plans to update the design system UI kit?

This would be very helpful for those who want to ensure their mockups are always utilizing the latest design system assets.

**Comment by marekdlugos** [comment]
I wanted to say the same. There is a lot of designers that uses your the Sketch file to mockup things but it was updated in April last time.

Btw. the file is quite poorly designed in terms of symbol overrides, layers & groups naming and etc..

**Comment by engai** [comment]
Hey @cceremuga and @marekdlugos , as of Friday 1/5, the new sketch UI kit for Winter '18 has been released.

Our sincere apologies for the delay of this release to the public. We're looking into ways we can better collaborate on the UI kit and are working on dedicating more resources into this project. At the same time, we appreciate your feedback and will work to improve the design of the kit for future releases.
