### ISSUE TITLE
Take advantage of sketch libraries!

### ISSUE THREAD

**Issue by chrisarg0** [salesforce-ux/design-system-ui-kit#11]
Would be great if we could have this refreshed the latest release and take advantage of Sketch Libraries and symbols!

**Comment by aweibel** [comment]
Hi @chrisarg0. Great news! You can currently add this Sketch file as a library by going to Preferences > Libraries > Add Library.

**Comment by chrisarg0** [comment]
Awesome news @aweibel - thanks to you and your team for putting time into the UI kit update!
