### ISSUE TITLE
Please Post PDF

### ISSUE THREAD

**Issue by mmoo9154** [salesforce-ux/design-system-ui-kit#15]
Dear SFDX, because Sketch is a Mac only (and commercial) product, would you please consider publishing a PDF of the design kit?  Thank you!

**Comment by mmoo9154** [comment]
Until someone with a Mac gets to this...  I was able to generate a PDF by opening the sketch file with https://www.photopea.com/ then export to SVG. I opened the SVG with Chrome and printed to PDF.

Here it is: [sketch-ui-kit-winter18-sketch.pdf](https://github.com/salesforce-ux/design-system-ui-kit/files/1789212/sketch-ui-kit-winter18-sketch.pdf)

**Comment by engai** [comment]
Hi @mmoo9154, we recognize that Sketch is a paid Mac only app, and would love to be more inclusive of all of our users. What is your use case for a PDF and the overall goal?

**Comment by aweibel** [comment]
@mmoo9154 We will include exported PDF files as part of each release from now on.
