### ISSUE TITLE
Not so much an issue as a question RE: Contribution

### ISSUE THREAD

**Issue by lixelart** [salesforce-ux/design-system-ui-kit#18]
I'd love to be able to start contributing back some work I am doing to make the sketch library more efficient to use for my team. 

What is the best way to do that?

Small chunks of work? Big chunks of work?

**Comment by lixelart** [comment]
@engai @aweibel (I'm not sure if you two are the right, but you two just did the Summer 18 push soooo... 🤷‍♀️😅

**Comment by aweibel** [comment]
Hi @lixelart. Contributions are welcome. Small chunks of work are definitely easier to review.

We just released a lot of major changes so make sure what you're looking to do is 1) synced with the latest and 2) it doesn't already exist in the new version.

Thanks!

**Comment by lixelart** [comment]
Oh I am super excited about the new release, have been taking a look at it pretty closely today. You guys have done a lot with this release to make it easier to use. I just want to keep building on all of that!
