### ISSUE TITLE
What can Windows users do?

### ISSUE THREAD

**Issue by imsergiobernal** [salesforce-ux/design-system-ui-kit#26]
Hi everyone, I'm a web developer beginner. This is the first time that I come to Design Systems. I decided to give a try to SLDS for my project which has very similar personas.

The thing is, I'm a Windows 10 user, and I begin to use Invision, AdobeXD and even Photoshop (with Craft plugin for Invision) for prototyping. I didn't decided my final setup but, I'm suffering with this kind of dispersion.

I want to proto with SLDS before entering to develop in React.

What do you suggest to me? Thanks!

**Comment by aweibel** [comment]
Hi @imsergiobernal. I'm glad you're interested in designing with SLDS. Our designers don't design with Adobe XD or any other design tool that works on Windows so we are unable to support resources for that operating system. There are still a number of ways to design or prototype without having Sketch. 

You can prototype using the design system framework here https://github.com/salesforce-ux/design-system or by using the starter kit https://github.com/salesforce-ux/design-system-starter-kit no matter if you use a Mac, Chromebook or Windows machine.

In this next release, there will also be PDF exports of all the artboards. You could utilize those as well.

If @ghostskull789 creates his own repository to support his XD kit, that's another potential source for you.

Thanks for the feedback.
