### ISSUE TITLE
how can i build my own "add-library?url"  like salesforce ux team?

### ISSUE THREAD

**Issue by uwings** [salesforce-ux/design-system-ui-kit#29]
becase sketch cloud update is bad .  so i want use it like salesforce UX team , use my own domain, host.   but ...  i failed.

**Comment by aweibel** [comment]
Hi @uwings. We actually wrote an article about that! Read more here: https://medium.com/@almonk/how-to-automatically-update-your-sketch-libraries-using-rss-1a6b6be3d72f

**Comment by uwings** [comment]
Thank you Very much, it's amazing and useful .   half mouth ago i just use http, so i failed.
