### ISSUE TITLE
SLDS Icons Add Library Link is Broken

### ISSUE THREAD

**Issue by joshlequire** [salesforce-ux/design-system-ui-kit#35]
STEPS TO REPRODUCE:
1) Paste link into Chrome `sketch://add-library?url=https://www.lightningdesignsystem.com/sketch-library-icons-rss.xml`

EXPECTED RESULTS
Add library to Sketch

ACTUAL RESULTS
Sketch returns message "An error occurred in retrieving update information. Please try again later."

WORKAROUND
Download library manually from this repo and add.

**Comment by aweibel** [comment]
Thanks for finding this, @joshlequire. We'll fix this typo in the next build. If you'd like a workaround in the meantime, you can remove the "s" from "icons" in the URL so it reads `sketch://add-library?url=https://www.lightningdesignsystem.com/sketch-library-icon-rss.xml`

@ryukelson1

**Comment by joshlequire** [comment]
Awesome, and thank you @aweibel ! I did not notice that subtle 's' yesterday but was able to download the library and load it to sketch locally. However, this link works perfectly, and I've since subscribed this feed and removed my local library.
