### ISSUE TITLE
README.md - Figma resource links 404

### ISSUE THREAD

**Issue by thedanfernandez** [salesforce-ux/design-system-ui-kit#37]
### Issue

These two links are broken in the [Readme Line 48](https://github.com/salesforce-ux/design-system-ui-kit/blame/master/README.md#L48)

> If you do not have Sketch, you can use the Framer SLDS UI Kit or Figma SLDS Components for Web and Figma SLDS Icons libraries, however, they may not be as up-to-date as the Sketch files.

1. **Figma SLDS Components for Web** - https://www.figma.com/file/5dgFdCHB6FGjfOPAZEDNVK/Lightning-Design-System-Components-for-Web?node-id=0%3A1 
2. **Figma SLDS Icons** - https://www.figma.com/file/5dgFdCHB6FGjfOPAZEDNVK/Lightning-Design-System-Components-for-Web?node-id=0%3A1 

### Current Behavior

Figma returns a 404, note reference to potential permissions issue:
> If you expected to see a file here you may not have permission to access it. Please ask the owner to update the file permissions. They can read more about that on our Help Page, or email us at support@figma.com if they have questions.

### Resolution

1. Update permissions (per Figma message above) 
2. Update the URLs if they are incorrect

**Comment by abhidesignUX** [comment]
Hi Dan,
We  are working on Salesforce project and we need help to get Figma UI kit of lightning web components, that link is still not working. Could you please help and guide  
Thanks
Abhi

**Comment by petrslobodzian** [comment]
Hi Abhi, I believe that you should be still able to open the original .sketch UI kit (https://github.com/salesforce-ux/design-system-ui-kit/blob/master/SLDS%20Icon%20Library.sketch) and import it into Figma. I just tried it and it seems to work). Cheers. Petr

**Comment by abhidesignUX** [comment]
Hi Petr,
Thanks for your suggestions.
It worked for me now.
Appreciate you help ☺

Thanks
Best regards
Abhi
UX Design

**Comment by petrslobodzian** [comment]
Happy to help.

**Comment by aweibel** [comment]
The previous Figma link was for internal employees. Since you're not part of our enterprise account, you correctly encountered an access error. We recently published a public version of our kits so we updated the link to point to the public files.
