### ISSUE TITLE
Libraries for Figma not working

### ISSUE THREAD

**Issue by bea-ibeas-stockcrowd** [salesforce-ux/design-system-ui-kit#38]
Hi,

I would like to access salesforce's library for Figma (Figma SLDS Components for Web and Figma SLDS Icons) but when clicking the link this message appears "File not found. Either this file doesn’t exist or you don’t have permission to view it. Ask the file owner to verify the link and/or update permissions."

Moreover, is there a library for Adobe XD?

Thanks in advance,

**Comment by aweibel** [comment]
The previous Figma link was for internal employees. Since you're not part of our enterprise account, you encountered an access error. We recently published a public version of our kits so we updated the link to point to the public files.

We have no plans to have a kit for Adobe XD currently.
