### ISSUE TITLE
Fonts

### ISSUE THREAD

**Issue by abarrow** [salesforce-ux/design-system-ui-kit#4]
I followed below instructions but I don't see fonts (or the indicated folder)

1 Download the Design System Zip
2 Find the fonts located in the **/assets/fonts directory**
3 Install the fonts on your system

**Comment by tsheiner** [comment]
OK, I think this is an issue with the clarity of the instructions.

This repo has the Sketch UI kit file.

However, to get the fonts you need to download the design system itself, which you can do from this page: https://www.lightningdesignsystem.com/downloads/ then scroll to 'Design System Zip.'

Once you download and expand that file you will find the fonts in asset directory.

**Comment by abarrow** [comment]
Ah I see... thanks for that!
